# Generated by Django 5.1.4 on 2025-01-07 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='manufacturer',
            new_name='empresa',
        ),
    ]
