# Generated by Django 5.1.4 on 2025-01-07 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_manufacturer_producto_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.empresa'),
        ),
    ]
